# Generated by Django 2.2.2 on 2019-06-16 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='Category')),
                ('cat_title', models.CharField(max_length=250)),
                ('cat_overview', models.CharField(max_length=500)),
                ('cat_slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=255)),
                ('tutorial_timestamp', models.DateTimeField(auto_now_add=True)),
                ('tutorial_views', models.PositiveIntegerField(default=1)),
                ('tutorial_content', models.TextField()),
                ('tutorial_thumbnail', models.ImageField(blank=True, null=True, upload_to='SubSubCategory')),
                ('tutorial_slug', models.SlugField(unique=True)),
                ('tutorial_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_image', models.ImageField(blank=True, null=True, upload_to='SubCategory')),
                ('sub_cat_title', models.CharField(max_length=255)),
                ('sub_cat_overview', models.CharField(max_length=500)),
                ('sub_cat_slug', models.SlugField(unique=True)),
                ('sub_cat_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub categories',
            },
        ),
    ]
